name: Sync to Hugging Face
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Add remote
      env:
        HF: ${{ secrets.HF }}
      run: git remote add space https://diogocarapito:$HF@huggingface.co/spaces/diogocarapito/mlops_demo
    - name: Push to hub
      env:
        HF: ${{ secrets.HF }}
      run: git push --force https://diogocarapito:$HF@huggingface.co/spaces/diogocarapito/mlops_demo main
